export const DEFAULT_ROLES = ["OWNER", "ADMIN", "CASHIER", "WAREHOUSE", "ACCOUNTANT", "BRANCH_MANAGER"] as const;

export const DEFAULT_PERMISSIONS = [
  { key: "dashboard.read", name: "Read dashboard" },
  { key: "sales.read", name: "Read sales/transactions" },
  { key: "sales.write", name: "Create sales/transactions" },
  { key: "sales.delete", name: "Delete sales/transactions" },
  { key: "products.read", name: "Read products" },
  { key: "products.write", name: "Create/update products" },
  { key: "products.delete", name: "Delete products" },
  { key: "products.export", name: "Export products (CSV/Excel/PDF)" },
  { key: "products.import", name: "Import products (CSV/Excel)" },
  { key: "products.transfer", name: "Transfer stock between warehouses/branches" },
  { key: "products.opname", name: "Stock opname / cycle count" },
  { key: "products.adjustment", name: "Stock adjustment" },
  { key: "products.price.manage", name: "Manage product prices (branch/wholesale/member)" },
  { key: "products.discount.manage", name: "Manage product discounts/promos (amount/percent/BOGO/bundle)" },
  { key: "products.analytics.read", name: "Read product analytics dashboard" },
  { key: "products.ai.read", name: "Read AI recommendations (heuristic)" },
  { key: "products.barcode.read", name: "Read barcode/label tools" },
  { key: "products.barcode.generate", name: "Generate product barcodes/QR codes" },
  { key: "products.barcode.print", name: "Print/export barcode labels" },
  { key: "products.expired.read", name: "Read expired/batch reports" },
  { key: "products.expired.update", name: "Update product batches/expired date" },
  { key: "products.ocr.scan", name: "Scan expired date from photo (OCR)" },
  { key: "branches.read", name: "Read branches" },
  { key: "branches.write", name: "Create/update branches" },
  { key: "branches.delete", name: "Delete branches" },
  { key: "staff.read", name: "Read staff/users" },
  { key: "staff.write", name: "Create/update staff/users" },
  { key: "staff.delete", name: "Delete staff/users" },
  { key: "customers.read", name: "Read customers" },
  { key: "customers.write", name: "Create/update customers" },
  { key: "customers.delete", name: "Delete customers" },
  { key: "suppliers.read", name: "Read suppliers" },
  { key: "suppliers.write", name: "Create/update suppliers" },
  { key: "suppliers.delete", name: "Delete suppliers" },
  { key: "inventory.read", name: "Read inventory" },
  { key: "inventory.write", name: "Create/update inventory" },
  { key: "inventory.delete", name: "Delete inventory" },
  { key: "reports.read", name: "Read reports" },
  { key: "settings.read", name: "Read settings" },
  { key: "settings.write", name: "Update settings" },
  { key: "billing.read", name: "Read billing" },
] as const;

export const DEFAULT_ROLE_PERMISSION_MATRIX: Record<(typeof DEFAULT_ROLES)[number], string[]> = {
  OWNER: [
    "dashboard.read",
    "sales.read",
    "sales.write",
    "sales.delete",
    "products.read",
    "products.write",
    "products.delete",
    "products.export",
    "products.import",
    "products.transfer",
    "products.opname",
    "products.adjustment",
    "products.price.manage",
    "products.discount.manage",
    "products.analytics.read",
    "products.ai.read",
    "products.barcode.read",
    "products.barcode.generate",
    "products.barcode.print",
    "products.expired.read",
    "products.expired.update",
    "products.ocr.scan",
    "branches.read",
    "branches.write",
    "branches.delete",
    "staff.read",
    "staff.write",
    "staff.delete",
    "customers.read",
    "customers.write",
    "customers.delete",
    "suppliers.read",
    "suppliers.write",
    "suppliers.delete",
    "inventory.read",
    "inventory.write",
    "inventory.delete",
    "reports.read",
    "settings.read",
    "settings.write",
    "billing.read",
  ],
  ADMIN: [
    "dashboard.read",
    "sales.read",
    "sales.write",
    "sales.delete",
    "products.read",
    "products.write",
    "products.delete",
    "products.export",
    "products.import",
    "products.transfer",
    "products.opname",
    "products.adjustment",
    "products.price.manage",
    "products.discount.manage",
    "products.analytics.read",
    "products.ai.read",
    "products.barcode.read",
    "products.barcode.generate",
    "products.barcode.print",
    "products.expired.read",
    "products.expired.update",
    "products.ocr.scan",
    "branches.read",
    "branches.write",
    "branches.delete",
    "staff.read",
    "staff.write",
    "staff.delete",
    "customers.read",
    "customers.write",
    "customers.delete",
    "suppliers.read",
    "suppliers.write",
    "suppliers.delete",
    "inventory.read",
    "inventory.write",
    "inventory.delete",
    "reports.read",
    "settings.read",
    "settings.write",
    "billing.read",
  ],
  CASHIER: ["dashboard.read", "sales.read", "sales.write", "products.read", "customers.read"],
  WAREHOUSE: [
    "dashboard.read",
    "branches.read",
    "products.read",
    "products.write",
    "products.transfer",
    "products.opname",
    "products.adjustment",
    "products.analytics.read",
    "products.barcode.read",
    "products.barcode.generate",
    "products.barcode.print",
    "products.expired.read",
    "products.expired.update",
    "products.ocr.scan",
    "inventory.read",
    "inventory.write",
  ],
  ACCOUNTANT: ["dashboard.read", "branches.read", "sales.read", "reports.read", "products.read", "customers.read", "suppliers.read", "billing.read"],
  BRANCH_MANAGER: [
    "dashboard.read",
    "sales.read",
    "sales.write",
    "branches.read",
    "products.read",
    "products.write",
    "products.export",
    "products.transfer",
    "products.opname",
    "products.adjustment",
    "products.price.manage",
    "products.discount.manage",
    "products.analytics.read",
    "products.ai.read",
    "products.barcode.read",
    "products.barcode.generate",
    "products.barcode.print",
    "products.expired.read",
    "products.expired.update",
    "products.ocr.scan",
    "customers.read",
    "customers.write",
    "suppliers.read",
    "suppliers.write",
    "inventory.read",
    "inventory.write",
    "reports.read",
    "settings.read",
  ],
};
