export const DEFAULT_ROLES = ["OWNER", "ADMIN", "CASHIER", "WAREHOUSE", "ACCOUNTANT", "BRANCH_MANAGER"] as const;

export const DEFAULT_PERMISSIONS = [
  { key: "dashboard.read", name: "Read dashboard" },
  { key: "sales.read", name: "Read sales/transactions" },
  { key: "sales.write", name: "Create sales/transactions" },
  { key: "sales.delete", name: "Delete sales/transactions" },
  { key: "products.read", name: "Read products" },
  { key: "products.write", name: "Create/update products" },
  { key: "products.delete", name: "Delete products" },
  { key: "branches.read", name: "Read branches" },
  { key: "branches.write", name: "Create/update branches" },
  { key: "branches.delete", name: "Delete branches" },
  { key: "staff.read", name: "Read staff/users" },
  { key: "staff.write", name: "Create/update staff/users" },
  { key: "staff.delete", name: "Delete staff/users" },
  { key: "customers.read", name: "Read customers" },
  { key: "customers.write", name: "Create/update customers" },
  { key: "customers.delete", name: "Delete customers" },
  { key: "suppliers.read", name: "Read suppliers" },
  { key: "suppliers.write", name: "Create/update suppliers" },
  { key: "suppliers.delete", name: "Delete suppliers" },
  { key: "inventory.read", name: "Read inventory" },
  { key: "inventory.write", name: "Create/update inventory" },
  { key: "inventory.delete", name: "Delete inventory" },
  { key: "reports.read", name: "Read reports" },
  { key: "settings.read", name: "Read settings" },
  { key: "settings.write", name: "Update settings" },
  { key: "billing.read", name: "Read billing" },
] as const;

export const DEFAULT_ROLE_PERMISSION_MATRIX: Record<(typeof DEFAULT_ROLES)[number], string[]> = {
  OWNER: [
    "dashboard.read",
    "sales.read",
    "sales.write",
    "sales.delete",
    "products.read",
    "products.write",
    "products.delete",
    "branches.read",
    "branches.write",
    "branches.delete",
    "staff.read",
    "staff.write",
    "staff.delete",
    "customers.read",
    "customers.write",
    "customers.delete",
    "suppliers.read",
    "suppliers.write",
    "suppliers.delete",
    "inventory.read",
    "inventory.write",
    "inventory.delete",
    "reports.read",
    "settings.read",
    "settings.write",
    "billing.read",
  ],
  ADMIN: [
    "dashboard.read",
    "sales.read",
    "sales.write",
    "sales.delete",
    "products.read",
    "products.write",
    "products.delete",
    "branches.read",
    "branches.write",
    "branches.delete",
    "staff.read",
    "staff.write",
    "staff.delete",
    "customers.read",
    "customers.write",
    "customers.delete",
    "suppliers.read",
    "suppliers.write",
    "suppliers.delete",
    "inventory.read",
    "inventory.write",
    "inventory.delete",
    "reports.read",
    "settings.read",
    "settings.write",
    "billing.read",
  ],
  CASHIER: ["dashboard.read", "sales.read", "sales.write", "products.read", "customers.read"],
  WAREHOUSE: ["dashboard.read", "branches.read", "products.read", "products.write", "inventory.read", "inventory.write"],
  ACCOUNTANT: ["dashboard.read", "branches.read", "sales.read", "reports.read", "products.read", "customers.read", "suppliers.read", "billing.read"],
  BRANCH_MANAGER: [
    "dashboard.read",
    "sales.read",
    "sales.write",
    "branches.read",
    "products.read",
    "products.write",
    "customers.read",
    "customers.write",
    "suppliers.read",
    "suppliers.write",
    "inventory.read",
    "inventory.write",
    "reports.read",
    "settings.read",
  ],
};
